### ISSUE TITLE
does not work on pypy 3.2

### ISSUE THREAD

**Issue by allspace** [crossbario/crossbar#351]
CentOS 6.6 (64-bit)
download and install pypy 3.2 portable version
install pip
install crossbar using pip
create template application:
crossbar init --template hello:python --appdir hello
run the application:
crossbar start --cbdir /root/hello/.crossbar
Get output as below:

2015-05-24 06:21:16-0400 [Controller  69596] ==================== Crossbar.io ====================

2015-05-24 06:21:16-0400 [Controller  69596] Crossbar.io 0.10.4 starting
2015-05-24 06:21:16-0400 [Controller  69596] Running on PyPy using EPollReactor reactor
2015-05-24 06:21:16-0400 [Controller  69596] Starting from node directory /root/hello/.crossbar
2015-05-24 06:21:17-0400 [Controller  69596] Traceback (most recent call last):
2015-05-24 06:21:17-0400 [Controller  69596]   File "/root/pypy3-2.4-linux_x86_64-portable/site-packages/autobahn/twisted/wamp.py", line 53, in <module>
2015-05-24 06:21:17-0400 [Controller  69596]     from twisted.application import service
2015-05-24 06:21:17-0400 [Controller  69596] ImportError: No module named twisted.application
2015-05-24 06:21:17-0400 [Controller  69596]
2015-05-24 06:21:17-0400 [Controller  69596] During handling of the above exception, another exception occurred:
2015-05-24 06:21:17-0400 [Controller  69596]
2015-05-24 06:21:17-0400 [Controller  69596] Traceback (most recent call last):
2015-05-24 06:21:17-0400 [Controller  69596]   File "/root/pypy3-2.4-linux_x86_64-portable/bin/crossbar", line 11, in <module>
2015-05-24 06:21:17-0400 [Controller  69596]     sys.exit(run())
2015-05-24 06:21:17-0400 [Controller  69596]   File "/root/pypy3-2.4-linux_x86_64-portable/site-packages/crossbar/controller/cli.py", line 665, in run
2015-05-24 06:21:17-0400 [Controller  69596]     options.func(options)
2015-05-24 06:21:17-0400 [Controller  69596]   File "/root/pypy3-2.4-linux_x86_64-portable/site-packages/crossbar/controller/cli.py", line 402, in run_command_start
2015-05-24 06:21:17-0400 [Controller  69596]     from crossbar.controller.node import Node
2015-05-24 06:21:17-0400 [Controller  69596]   File "/root/pypy3-2.4-linux_x86_64-portable/site-packages/crossbar/controller/node.py", line 51, in <module>
2015-05-24 06:21:17-0400 [Controller  69596]     from crossbar.controller.process import NodeControllerSession
2015-05-24 06:21:17-0400 [Controller  69596]   File "/root/pypy3-2.4-linux_x86_64-portable/site-packages/crossbar/controller/process.py", line 62, in <module>
2015-05-24 06:21:17-0400 [Controller  69596]     from crossbar.common.process import NativeProcessSession
2015-05-24 06:21:17-0400 [Controller  69596]   File "/root/pypy3-2.4-linux_x86_64-portable/site-packages/crossbar/common/process.py", line 67, in <module>
2015-05-24 06:21:17-0400 [Controller  69596]     from autobahn.twisted.wamp import ApplicationSession
2015-05-24 06:21:17-0400 [Controller  69596]   File "/root/pypy3-2.4-linux_x86_64-portable/site-packages/autobahn/twisted/wamp.py", line 57, in <module>
2015-05-24 06:21:17-0400 [Controller  69596]     __all__.pop(__all__.index("Service"))
2015-05-24 06:21:17-0400 [Controller  69596] AttributeError: 'tuple' object has no attribute 'pop'

**Comment by oberstet** [comment]
python 3 is not yet supported

**Comment by a904guy** [comment]
Is this still the case? After pip install this is the local bin script? 

The shebang specifies 3.4, guessing that is from the local env of the pip install?

```
✗ cat /usr/local/bin/crossbar 
#!/usr/bin/python3.4
# EASY-INSTALL-ENTRY-SCRIPT: 'crossbar==0.10.4','console_scripts','crossbar'
__requires__ = 'crossbar==0.10.4'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('crossbar==0.10.4', 'console_scripts', 'crossbar')()
    )
```

**Comment by a904guy** [comment]
Confirmed forcing python2 env works.

Any plans near term plans for python3 support?

**Comment by goeddea** [comment]
We've sponsored work for getting Twisted (the framework that Crossbar.io uses) to work on Python 3. These changes are making their way through the Twisted release process at the moment. 
So while I can't give you a definitive timeline, Python 3 support is underway.

**Comment by hawkowl** [comment]
Hi,

This won't work on PyPy 3.2, as Twisted only supports Python 3.3 and up (3.2 didn't support `b""` or `u""` so it was very hard to).

Currently, a large amount of functionality works on Python 3.3/3.4, providing you have trunk versions of Autobahn|Python (patched with https://github.com/tavendo/AutobahnPython/pull/430 in the meantime) and Twisted (of which a version that will work with Autobahn+Crossbar is due to be released early next week, you can get tarballs from http://twistedmatrix.com/Releases/pre/15.3.0pre1/ ).

I'm working on getting more and more working in Crossbar to make Python 3 a first-class platform, but if you want the speed of PyPy, you will have to remain on Python 2 or wait for a PyPy targeting Python 3.3 (of which work is underway).

**Comment by a904guy** [comment]
Alright, Thank you for the updates, much appreciated!

**Comment by tebanep** [comment]
Unfortunately PyPy3.3 is taking forever... Hope they can some additional support. I'm learning how to use cffi for trying to help.
