### ISSUE TITLE
Crossbar doesn't work with autobahn 0.11.0

### ISSUE THREAD

**Issue by jonclare** [crossbario/crossbar#542]
It looks like longpoll.py has been removed from autobahn/twisted and Crossbar appears to depend on this.

`2015-12-10T16:56:11+0000 [Controller   7000]   File "c:\python27\lib\site-packages\crossbar\twisted\resource.py", line 42, in <module>`

`2015-12-10T16:56:11+0000 [Controller   7000]     from autobahn.twisted import longpoll`

`2015-12-10T16:56:11+0000 [Controller   7000] ImportError: cannot import name longpoll`

**Comment by meejah** [comment]
Until there is a new crossbar release unfortunately you have two options: downgrade Autobahn (to 0.10.9) or upgrade to crossbar master. To downgrade autobahn:

```
pip uninstall autobahn
pip install autobahn==0.10.9
```

**Comment by oberstet** [comment]
yeah, sorry. fixed in https://pypi.python.org/pypi/crossbar/0.11.2
