### ISSUE TITLE
WAMP Internal Error (__init__() got an unexpected keyword argument 'subscription_revocation')

### ISSUE THREAD

**Issue by garethbult** [crossbario/crossbar#343]
I'm working on on 10.1 but get this message when I upgrade to 10.4

Only affects Python clients, JS clients are Ok.

Any ideas?

I see a similar issue documented on 0.9.3 .. but the suggested patch for that doesn't seem to apply any more ...

**Comment by oberstet** [comment]
pls update your AutobahnPython

**Comment by garethbult** [comment]
Gah! I thought I had, but you're right, it's still showing 10.1 !!
System upgrade has now defaulted pip to pip3 rather than pip2, so it only updated autobahn for python3 and not python2 .. seems to work now!

tvm!  :)

**Comment by oberstet** [comment]
np;) good to hear it works for you now.
