### ISSUE TITLE
Update docs: Python2 is no longer supported

### ISSUE THREAD

**Issue by VisiBoost** [crossbario/crossbar#1332]
After making security upgrades on system (Ubuntu 16.04 - x86_64), Crossbar stop working.

I make npm and crossbar updates too : 
`npm update`
`pip install --upgrade crossbar`

But still getting error, even when just making a `crossbar version` call : 

> Traceback (most recent call last):
  File "/home/www/gmm_pypy_env/bin/crossbar", line 11, in <module>
    sys.exit(run())
  File "/home/www/gmm_pypy_env/site-packages/crossbar/__init__.py", line 172, in run
    _personalities = personalities()
  File "/home/www/gmm_pypy_env/site-packages/crossbar/__init__.py", line 205, in personalities
    from crossbar import personality as standalone
  File "/home/www/gmm_pypy_env/site-packages/crossbar/personality.py", line 40, in <module>
    from crossbar.node import node
  File "/home/www/gmm_pypy_env/site-packages/crossbar/node/node.py", line 52, in <module>
    from crossbar.node.controller import NodeController
  File "/home/www/gmm_pypy_env/site-packages/crossbar/node/controller.py", line 38, in <module>
    from shutil import which
ImportError: cannot import name 'which'

I'am using Pypy virtualenv, all was working fine this morning before updates ; here my versions : 

> Python 2.7.13 (6.0.0+dfsg-1~ppa1~ubuntu16.04, Apr 28 2018, 03:15:13)
[PyPy 6.0.0 with GCC 5.4.0 20160609]

I tried to make new virtualenv or use CPython instead but still getting the same problem ... have you any idea ?

**Comment by om26er** [comment]
Crossbar no longer supports python2, please use Python3.

**Comment by VisiBoost** [comment]
Trying to switch to Python 3.5 thanks.

I think you will have to update documentation like here : [https://crossbar.io/docs/Installation-on-Linux/](url)

**Comment by oberstet** [comment]
yeah, the docs are misleading (wrong) now: sorry!

> fwiw, you could also run the last version of crossbar with python 2 support: `pip install crossbar==18.4.1`

**Comment by Mdrbhatti** [comment]
I just spent the last 2 hours wondering why crossbar wasn't working with python-2.7 (as stated in the documentation for both Windows/Linux). An update in the documentation would be highly appreciated :(

**Comment by ov7a** [comment]
Please, remove versions which do not support python-2.7 from pip2. Or release a new version with a proper exception message. Spent hours trying to fix ImportError.

**Comment by oberstet** [comment]
@ov7a https://github.com/crossbario/crossbar/blob/master/setup.py#L118

**Comment by ov7a** [comment]
@oberstet 
```
ov7a@ov7a-desktop:~$ pip --version
pip 8.1.1 from /usr/lib/python2.7/dist-packages (python 2.7)
ov7a@ov7a-desktop:~$ pip -q install crossbar
ov7a@ov7a-desktop:~$ pip list | grep crossbar
crossbar (18.7.2)
```
