### ISSUE TITLE
Crossbar start not working in Python 3.4

### ISSUE THREAD

**Issue by kracekumar** [crossbario/crossbar#324]
#### Crossbar start

```
(ws)➜  ~  crossbar start                        
Traceback (most recent call last):
  File "/home/kracekumar/.virtualenvs/ws/bin/crossbar", line 9, in <module>
    load_entry_point('crossbar==0.10.4', 'console_scripts', 'crossbar')()
  File "/home/kracekumar/.virtualenvs/ws/lib/python3.4/site-packages/crossbar/controller/cli.py", line 665, in run
    options.func(options)
  File "/home/kracekumar/.virtualenvs/ws/lib/python3.4/site-packages/crossbar/controller/cli.py", line 387, in run_command_start
    from crossbar.twisted.processutil import DefaultSystemFileLogObserver
  File "/home/kracekumar/.virtualenvs/ws/lib/python3.4/site-packages/crossbar/twisted/processutil.py", line 38, in <module>
    from twisted.internet.endpoints import _WrapIProtocol, ProcessEndpoint
ImportError: cannot import name 'ProcessEndpoint'
```

#### Python version

```
(ws)➜  ~  python --version
Python 3.4.0
```

#####  Pip freeze
```
(ws)➜  ~  pip freeze
Jinja2==2.7.3
MarkupSafe==0.23
PyTrie==0.2
PyYAML==3.11
Pygments==2.0.2
Twisted==15.1.0
autobahn==0.10.4
cffi==0.9.2
characteristic==14.3.0
crossbar==0.10.4
cryptography==0.8.2
ipython==3.1.0
mistune==0.5.1
netaddr==0.7.14
pyOpenSSL==0.15.1
pyasn1==0.1.7
pyasn1-modules==0.0.5
pycparser==2.12
requests==2.7.0
service-identity==14.0.0
shutilwhich==1.1.0
six==1.9.0
treq==15.0.0
txaio==1.0.0
zope.interface==4.1.2
```

#### Crossbar config

```
(ws)➜  .crossbar  cat config.json 

{
   "controller": {
   },
   "workers": [
      {
         "type": "router",
         "realms": [
            {
               "name": "realm1",
               "roles": [
                  {
                     "name": "anonymous",
                     "permissions": [
                        {
                           "uri": "*",
                           "publish": true,
                           "subscribe": true,
                           "call": true,
                           "register": true
                        }
                     ]
                  }
               ]
            }
         ],
         "transports": [
            {
               "type": "web",
               "endpoint": {
                  "type": "tcp",
                  "port": 8080
               },
               "paths": {
                  "/": {
                     "type": "static",
                     "directory": ".."
                  },
                  "ws": {
                     "type": "websocket"
                  }
               }
            }
         ]
      }
   ]
}

```

**Comment by meejah** [comment]
Currently, crossbar itself needs Python2 to run. Of course, any of your connected application components can use Python3.

**Comment by hawkowl** [comment]
Hi! As @meejah said, Crossbar the router only supports Python 2 right now, but you can write components in Python 3. I'm currently working on getting Crossbar working on Python 3.3+, and so far have some prototypes working, but it's not yet in a production state (needs more thorough testing + some upstream Twisted patches to land).
