### ISSUE TITLE
WSGI Host Service seems to be broken in 18.6.1

### ISSUE THREAD

**Issue by asodeur** [crossbario/crossbar#1355]
After updating to 18.6.1 hosting WSGI applications fails with:
```python
Traceback (most recent call last):
  File "c:\virtualenvs\weboptions_py3\lib\site-packages\twisted\internet\defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "c:\virtualenvs\weboptions_py3\lib\site-packages\twisted\internet\defer.py", line 1532, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
  File "c:\virtualenvs\weboptions_py3\lib\site-packages\twisted\internet\defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "c:\virtualenvs\weboptions_py3\lib\site-packages\crossbar\worker\transport.py", line 393, in _create_web_factory
    root_webservice = yield maybeDeferred(root_factory.create, self, '/', root_config)
--- <exception caught here> ---
  File "c:\virtualenvs\weboptions_py3\lib\site-packages\twisted\internet\defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "c:\virtualenvs\weboptions_py3\lib\site-packages\crossbar\webservice\wsgi.py", line 76, in create
    transport.reactor.addSystemEventTrigger('before', 'shutdown', pool.stop)
builtins.AttributeError: 'RouterWebTransport' object has no attribute 'reactor'
```

Last version I tried was 18.4.1 hence this might affect 18.5.x as well.

Andreas

**Comment by asodeur** [comment]
fixed in v18.10.1
