### ISSUE TITLE
'Register' object has no attribute 'correlation'

### ISSUE THREAD

**Issue by jmgurney** [crossbario/crossbar#1193]
Running latest release, v17.9.1.  Previously same config was working on 17.6.1, but need to upgrade due to broken CryptoSign channel binding previous to 17.9.1.

When starting up, I get lots of lines like:
2017-09-19T06:04:32+0000 [Controller  65543] Unhandled error in Deferred:                                                                                                                                         
2017-09-19T06:04:32+0000 [Controller  65543] Traceback (most recent call last):                                                                                                                                   
  File "/home/jmg/haws/t/src/crossbar/crossbar/router/router.py", line 252, in process                                                                                                                            
    self._dealer.processRegister(session, msg)                                                                                                                                                                    
  File "/home/jmg/haws/t/src/crossbar/crossbar/router/dealer.py", line 422, in processRegister                                                                                                                    
    txaio.add_callbacks(d, on_authorize_success, on_authorize_error)                                                                                                                                              
  File "/home/jmg/haws/t/lib/python2.7/site-packages/txaio/tx.py", line 491, in add_callbacks
    future.addCallbacks(callback, errback)                                                               
  File "/home/jmg/haws/t/lib/python2.7/site-packages/twisted/internet/defer.py", line 310, in addCallbacks
    self._runCallbacks()                                                                         
--- <exception caught here> ---                                                                                                                                                                                   
  File "/home/jmg/haws/t/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)                                               
  File "/home/jmg/haws/t/src/crossbar/crossbar/router/dealer.py", line 383, in on_authorize_success   
    correlation=register.correlation                                                                                                                                                                              
exceptions.AttributeError: 'Register' object has no attribute 'correlation'                              

Config is attached.
[config.txt](https://github.com/crossbario/crossbar/files/1313206/config.txt)

**Comment by jmgurney** [comment]
The master branch appears not to have this issue.

**Comment by PBonnema** [comment]
I'm having the same trouble with version 17.9.1 using the example config file. I've installed crossbar on windows 10 using python pip.

I'm also seeing the error
ReactorAlreadyInstalledError: reactor already installed
with most cmd line commands (even just crossbar version). This isn't a problem but it is just ugly.

**Comment by PBonnema** [comment]
I installed crossbar 17.9.2 by building from source and the original error as posted by the OP)got replaced by:

  File "c:\users\peter\downloads\nationsgamemockup\crossbar\crossbar\router\router.py", line 267, in process
    self._dealer.processRegister(session, msg)
  File "c:\users\peter\downloads\nationsgamemockup\crossbar\crossbar\router\dealer.py", line 503, in processRegister
    txaio.add_callbacks(d, on_authorize_success, on_authorize_error)
  File "c:\python27\lib\site-packages\txaio\tx.py", line 491, in add_callbacks
    future.addCallbacks(callback, errback)
  File "c:\python27\lib\site-packages\twisted\internet\defer.py", line 310, in addCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "c:\python27\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "c:\users\peter\downloads\nationsgamemockup\crossbar\crossbar\router\dealer.py", line 477, in on_authorize_success
    reply.correlation_is_last = True
exceptions.AttributeError: 'Registered' object has no attribute 'correlation_is_last'

**Comment by arnstein** [comment]
By using pip install I also get this error. Will install it from the master branch.

**Comment by oberstet** [comment]
fixed with 17.9.2 now on PyPI:

```console
(cpy362_4) oberstet@thinkpad-t430s:~$ ~/cpy362/bin/virtualenv ~/cpy362_5
Using base prefix '/home/oberstet/cpy362'
New python executable in /home/oberstet/cpy362_5/bin/python3.6
Also creating executable in /home/oberstet/cpy362_5/bin/python
Installing setuptools, pip, wheel...done.
(cpy362_4) oberstet@thinkpad-t430s:~$ source ~/cpy362_5/bin/activate
(cpy362_5) oberstet@thinkpad-t430s:~$ pip install crossbar
Collecting crossbar
  Downloading crossbar-17.9.2-py2.py3-none-any.whl (845kB)
    100% |████████████████████████████████| 849kB 974kB/s 
Collecting cryptography>=1.9 (from crossbar)
  Downloading cryptography-2.1.2-cp36-cp36m-manylinux1_x86_64.whl (2.2MB)
    100% |████████████████████████████████| 2.2MB 610kB/s 
Collecting pyOpenSSL>=17.1.0 (from crossbar)
  Using cached pyOpenSSL-17.3.0-py2.py3-none-any.whl
Collecting Jinja2>=2.9.6 (from crossbar)
  Using cached Jinja2-2.9.6-py2.py3-none-any.whl
Collecting constantly>=15.1.0 (from crossbar)
  Using cached constantly-15.1.0-py2.py3-none-any.whl
Collecting mistune>=0.7.4 (from crossbar)
  Using cached mistune-0.7.4-py2.py3-none-any.whl
Collecting PyNaCl>=1.1.2 (from crossbar)
  Using cached PyNaCl-1.1.2-cp36-cp36m-manylinux1_x86_64.whl
Collecting py-ubjson>=0.9.0 (from crossbar)
Collecting attrs>=17.2.0 (from crossbar)
  Using cached attrs-17.2.0-py2.py3-none-any.whl
Collecting u-msgpack-python>=2.4.1 (from crossbar)
  Using cached u_msgpack_python-2.4.1-py2.py3-none-any.whl
Collecting click>=6.7 (from crossbar)
  Using cached click-6.7-py2.py3-none-any.whl
Collecting sdnotify>=0.3.1 (from crossbar)
Collecting bitstring>=3.1.5 (from crossbar)
Collecting PyTrie>=0.3 (from crossbar)
Collecting PyYAML>=3.12 (from crossbar)
Collecting incremental>=17.5.0 (from crossbar)
  Using cached incremental-17.5.0-py2.py3-none-any.whl
Collecting enum34>=1.1.6 (from crossbar)
  Using cached enum34-1.1.6-py3-none-any.whl
Collecting h2>=3.0.1 (from crossbar)
  Using cached h2-3.0.1-py2.py3-none-any.whl
Collecting Twisted>=17.5.0 (from crossbar)
Collecting zope.interface>=4.4.2 (from crossbar)
  Using cached zope.interface-4.4.3-cp36-cp36m-manylinux1_x86_64.whl
Collecting pyasn1>=0.2.3 (from crossbar)
  Downloading pyasn1-0.3.7-py2.py3-none-any.whl (63kB)
    100% |████████████████████████████████| 71kB 10.1MB/s 
Collecting priority>=1.3.0 (from crossbar)
  Using cached priority-1.3.0-py2.py3-none-any.whl
Collecting autobahn>=17.9.3 (from crossbar)
  Using cached autobahn-17.9.3-py2.py3-none-any.whl
Collecting cbor>=1.0.0 (from crossbar)
Collecting shutilwhich>=1.1.0 (from crossbar)
Collecting ipaddress>=1.0.18 (from crossbar)
Requirement already satisfied: setuptools>=36.0.1 in ./cpy362_5/lib/python3.6/site-packages (from crossbar)
Collecting service-identity>=17.0.0 (from crossbar)
  Using cached service_identity-17.0.0-py2.py3-none-any.whl
Collecting idna<2.6,>=2.5 (from crossbar)
  Using cached idna-2.5-py2.py3-none-any.whl
Collecting netaddr>=0.7.19 (from crossbar)
  Using cached netaddr-0.7.19-py2.py3-none-any.whl
Collecting pyqrcode>=1.2.1 (from crossbar)
Collecting pyasn1-modules>=0.0.9 (from crossbar)
  Downloading pyasn1_modules-0.1.5-py2.py3-none-any.whl (60kB)
    100% |████████████████████████████████| 61kB 6.4MB/s 
Collecting txtorcon>=0.19.3 (from crossbar)
  Using cached txtorcon-0.19.3-py2.py3-none-any.whl
Collecting Pygments>=2.2.0 (from crossbar)
  Using cached Pygments-2.2.0-py2.py3-none-any.whl
Collecting txaio>=2.8.2 (from crossbar)
  Using cached txaio-2.8.2-py2.py3-none-any.whl
Collecting watchdog>=0.8.3 (from crossbar)
Collecting setproctitle>=1.1.10 (from crossbar)
Collecting treq>=17.3.1 (from crossbar)
  Using cached treq-17.8.0-py2.py3-none-any.whl
Collecting psutil>=5.2.2 (from crossbar)
  Downloading psutil-5.4.0.tar.gz (406kB)
    100% |████████████████████████████████| 409kB 2.6MB/s 
Collecting lmdb>=0.92 (from crossbar)
Collecting asn1crypto>=0.21.0 (from cryptography>=1.9->crossbar)
  Using cached asn1crypto-0.23.0-py2.py3-none-any.whl
Collecting six>=1.4.1 (from cryptography>=1.9->crossbar)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting cffi>=1.7; platform_python_implementation != "PyPy" (from cryptography>=1.9->crossbar)
  Downloading cffi-1.11.2-cp36-cp36m-manylinux1_x86_64.whl (419kB)
    100% |████████████████████████████████| 430kB 2.8MB/s 
Collecting MarkupSafe>=0.23 (from Jinja2>=2.9.6->crossbar)
Collecting sortedcontainers (from PyTrie>=0.3->crossbar)
  Using cached sortedcontainers-1.5.7-py2.py3-none-any.whl
Collecting hyperframe<6,>=5.0 (from h2>=3.0.1->crossbar)
  Using cached hyperframe-5.1.0-py2.py3-none-any.whl
Collecting hpack<4,>=2.3 (from h2>=3.0.1->crossbar)
  Using cached hpack-3.0.0-py2.py3-none-any.whl
Collecting hyperlink>=17.1.1 (from Twisted>=17.5.0->crossbar)
  Using cached hyperlink-17.3.1-py2.py3-none-any.whl
Collecting Automat>=0.3.0 (from Twisted>=17.5.0->crossbar)
  Using cached Automat-0.6.0-py2.py3-none-any.whl
Collecting argh>=0.24.1 (from watchdog>=0.8.3->crossbar)
  Using cached argh-0.26.2-py2.py3-none-any.whl
Collecting pathtools>=0.1.1 (from watchdog>=0.8.3->crossbar)
Collecting requests>=2.1.0 (from treq>=17.3.1->crossbar)
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting pycparser (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=1.9->crossbar)
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.1.0->treq>=17.3.1->crossbar)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests>=2.1.0->treq>=17.3.1->crossbar)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=2.1.0->treq>=17.3.1->crossbar)
  Using cached certifi-2017.7.27.1-py2.py3-none-any.whl
Building wheels for collected packages: psutil
  Running setup.py bdist_wheel for psutil ... done
  Stored in directory: /home/oberstet/.cache/pip/wheels/9d/a4/0b/a9a6155c8b775f3c45f2790171a2dab0a8503122ccb689cf29
Successfully built psutil
Installing collected packages: idna, asn1crypto, six, pycparser, cffi, cryptography, pyOpenSSL, MarkupSafe, Jinja2, constantly, mistune, PyNaCl, py-ubjson, attrs, u-msgpack-python, click, sdnotify, bitstring, sortedcontainers, PyTrie, PyYAML, incremental, enum34, hyperframe, hpack, h2, zope.interface, hyperlink, Automat, Twisted, pyasn1, priority, txaio, autobahn, cbor, shutilwhich, ipaddress, pyasn1-modules, service-identity, netaddr, pyqrcode, txtorcon, Pygments, argh, pathtools, watchdog, setproctitle, chardet, urllib3, certifi, requests, treq, psutil, lmdb, crossbar
Successfully installed Automat-0.6.0 Jinja2-2.9.6 MarkupSafe-1.0 PyNaCl-1.1.2 PyTrie-0.3 PyYAML-3.12 Pygments-2.2.0 Twisted-17.9.0 argh-0.26.2 asn1crypto-0.23.0 attrs-17.2.0 autobahn-17.9.3 bitstring-3.1.5 cbor-1.0.0 certifi-2017.7.27.1 cffi-1.11.2 chardet-3.0.4 click-6.7 constantly-15.1.0 crossbar-17.9.2 cryptography-2.1.2 enum34-1.1.6 h2-3.0.1 hpack-3.0.0 hyperframe-5.1.0 hyperlink-17.3.1 idna-2.5 incremental-17.5.0 ipaddress-1.0.18 lmdb-0.93 mistune-0.7.4 netaddr-0.7.19 pathtools-0.1.2 priority-1.3.0 psutil-5.4.0 py-ubjson-0.10.0 pyOpenSSL-17.3.0 pyasn1-0.3.7 pyasn1-modules-0.1.5 pycparser-2.18 pyqrcode-1.2.1 requests-2.18.4 sdnotify-0.3.2 service-identity-17.0.0 setproctitle-1.1.10 shutilwhich-1.1.0 six-1.11.0 sortedcontainers-1.5.7 treq-17.8.0 txaio-2.8.2 txtorcon-0.19.3 u-msgpack-python-2.4.1 urllib3-1.22 watchdog-0.8.3 zope.interface-4.4.3
(cpy362_5) oberstet@thinkpad-t430s:~$ cd /tmp/
(cpy362_5) oberstet@thinkpad-t430s:/tmp$ mkdir test
(cpy362_5) oberstet@thinkpad-t430s:/tmp$ cd test/
(cpy362_5) oberstet@thinkpad-t430s:/tmp/test$ crossbar init
Initializing application template 'default' in directory '/tmp/test'
Using template from '/home/oberstet/cpy362_5/lib/python3.6/site-packages/crossbar/templates/default'
Creating directory /tmp/test/.crossbar
Creating directory /tmp/test/web
Creating file /tmp/test/README.md
Creating file /tmp/test/.crossbar/config.json
Creating directory /tmp/test/web/js
Creating file /tmp/test/web/frontend.html
Creating file /tmp/test/web/index.html
Creating file /tmp/test/web/backend.html
Creating file /tmp/test/web/js/CHECKSUM.MD5
Creating file /tmp/test/web/js/autobahn.min.jgz
Creating file /tmp/test/web/js/CHECKSUM.SHA256
Creating file /tmp/test/web/js/autobahn.js
Creating file /tmp/test/web/js/LICENSE
Creating file /tmp/test/web/js/CHECKSUM.SHA1
Creating file /tmp/test/web/js/autobahn.min.js
Application template initialized

To start your node, run 'crossbar start --cbdir /tmp/test/.crossbar'

(cpy362_5) oberstet@thinkpad-t430s:/tmp/test$ crossbar start
2017-10-26T14:57:01+0200 [Controller  22014] New node key pair generated!
2017-10-26T14:57:01+0200 [Controller  22014] File permissions on node public key fixed!
2017-10-26T14:57:01+0200 [Controller  22014] File permissions on node private key fixed!
2017-10-26T14:57:01+0200 [Controller  22014]      __  __  __  __  __  __      __     __
2017-10-26T14:57:01+0200 [Controller  22014]     /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
2017-10-26T14:57:01+0200 [Controller  22014]     \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/
2017-10-26T14:57:01+0200 [Controller  22014]                                         
2017-10-26T14:57:01+0200 [Controller  22014] Version:     Crossbar.io COMMUNITY 17.9.2
2017-10-26T14:57:01+0200 [Controller  22014] Public Key:  51f4daf71597e695e42cfbf0271013d7e6b0e94876ec6d826f21cecd2505dba1
2017-10-26T14:57:01+0200 [Controller  22014] 
2017-10-26T14:57:01+0200 [Controller  22014] Node starting with personality "community" [crossbar.controller.node.Node]
2017-10-26T14:57:01+0200 [Controller  22014] Running from node directory "/tmp/test/.crossbar"
2017-10-26T14:57:01+0200 [Controller  22014] Node configuration loaded from "/tmp/test/.crossbar/config.json"
2017-10-26T14:57:01+0200 [Controller  22014] Controller process starting [CPython-EPollReactor] ..
2017-10-26T14:57:01+0200 [Controller  22014] No extra node router roles
2017-10-26T14:57:01+0200 [Controller  22014] RouterServiceSession ready [no on_ready configured]
2017-10-26T14:57:01+0200 [Controller  22014] Registered 20 procedures
2017-10-26T14:57:01+0200 [Controller  22014] Using default node shutdown triggers ['shutdown_on_worker_exit']
2017-10-26T14:57:01+0200 [Controller  22014] Configuring node from local configuration ...
2017-10-26T14:57:01+0200 [Controller  22014] Starting 1 workers ...
2017-10-26T14:57:01+0200 [Controller  22014] Router worker "worker-001" starting ..
2017-10-26T14:57:02+0200 [Router      22020] Started Router worker "worker-001" [crossbar.worker.router.RouterWorkerSession / CPython-EPollReactor]
2017-10-26T14:57:02+0200 [Router      22020] Router worker "worker-001" session 5456763303461604 initializing ..
2017-10-26T14:57:02+0200 [Router      22020] Registered 35 procedures
2017-10-26T14:57:02+0200 [Router      22020] Router worker "worker-001" session ready
2017-10-26T14:57:02+0200 [Controller  22014] Router worker "worker-001" process 22020 started
2017-10-26T14:57:02+0200 [Router      22020] RouterServiceSession ready [configured on_ready fired]
2017-10-26T14:57:02+0200 [Router      22020] Realm 'realm1' started
2017-10-26T14:57:02+0200 [Controller  22014] Router "worker-001": realm 'realm-001' (named 'realm1') started
2017-10-26T14:57:02+0200 [Router      22020] role role-001 on realm realm-001 started
2017-10-26T14:57:02+0200 [Controller  22014] Router "worker-001": role 'role-001' (named 'anonymous') started on realm 'realm-001'
2017-10-26T14:57:02+0200 [Router      22020] UniSocketServerFactory starting on 8080
2017-10-26T14:57:02+0200 [Controller  22014] Router "worker-001": transport 'transport-001' started
2017-10-26T14:57:02+0200 [Controller  22014] Local node configuration applied successfully!
^C2017-10-26T14:57:03+0200 [Controller  22014] Node shutdown requested ..
2017-10-26T14:57:03+0200 [Controller  22014] sending TERM to subprocess 22020
2017-10-26T14:57:03+0200 [Controller  22014] waiting for 22020 to exit...
2017-10-26T14:57:03+0200 [Router      22020] Native worker received SIGTERM - shutting down ..
2017-10-26T14:57:03+0200 [Router      22020] Shutdown of worker requested!
2017-10-26T14:57:04+0200 [Router      22020] Connection to node controller closed cleanly
2017-10-26T14:57:04+0200 [Router      22020] (TCP Port 8080 Closed)
2017-10-26T14:57:04+0200 [Controller  22014] Native worker connection closed cleanly.
2017-10-26T14:57:04+0200 [Controller  22014] Node worker worker-001 ended successfully
2017-10-26T14:57:04+0200 [Controller  22014] Checking for node shutdown: worker_exit_success=True, shutdown_requested=True, node_shutdown_triggers=['shutdown_on_worker_exit']
2017-10-26T14:57:04+0200 [Controller  22014] Node worker ended, and trigger 'shutdown_on_worker_exit' active
(cpy362_5) oberstet@thinkpad-t430s:/tmp/test$ 
```
